trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: dev_solution_name
    type: string
  - name: target_solution_name
    type: string

stages:
  - stage: extract
    displayName: Extract and Unpack
    jobs:
      - job: extract
        displayName: Extract and Unpack
        steps:
          - checkout: self
          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '**/$(parameters.dev_solution_name).zip'
              destinationFolder: '$(Build.SourcesDirectory)/$(parameters.target_solution_name)'
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.tool-installer.PowerPlatformToolInstaller@2
            displayName: 'Power Platform Tool Installer'
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.whoami.PowerPlatformWhoAmi@2
            displayName: 'Power Platform WhoAmI'
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: 'dev'
          - task: microsoft-IsvExpTools.PowerPlatform-BuildTools.export-solution.PowerPlatformExportSolution@2
            displayName: 'Power Platform Export Solution - ${{ parameters.dev_solution_name }}'
            inputs:
              authenticationType: PowerPlatformSPN
              PowerPlatformSPN: 'dev'
              SolutionName: ${{ parameters.dev_solution_name}}
              SolutionOutputFile: '$(Build.StagingDirectory)/${{ parameters.dev_solution_name }}_unmanaged.zip'
